# Synthetic Data Generator

In this notebook, we will show how to randomly generate synthetic labeled dataset for training Neural Networks.

For both models (Heston and rBergomi), the dataset should consist of ```features``` and ```labels```.

For the ```features```, we randomly draw from some specific distributions proposed by the paper; for the ```labels```, we use pricer functions to compute the IV.

**NB**: The pricer of Heston model is implemented by the package ```QuantLib```, we use it to save our life, while the pricer of rBergomi model, we refer to the implementation of (https://github.com/amuguruza/RoughFCLT/blob/master/rDonsker.ipynb) and (https://github.com/ryanmccrickerd/rough_bergomi). The pricer of rBergomi is based on a Monte-Carlo simulation, so it is extreeeeeeemly slow. So instead of generating $10^6$ samples as proposed in the paper, we only managed to generate $\sim 5 \times 10^5$.

## Generate Heston data

In [1]:
import os
import datetime
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

from tqdm import tqdm
tqdm.pandas()

import QuantLib as ql

In [2]:
from py_vollib.black_scholes.implied_volatility import implied_volatility
from py_lets_be_rational.exceptions import BelowIntrinsicException
import sklearn.utils
import logging

logging.basicConfig(format="%(asctime)s - %(levelname)s - %(message)s", level=logging.INFO)

### Define the Hestong pricer by using ```QuantLib```

In [3]:
def heston_pricer(lambd, vbar, eta, rho, v0, r, q, tau, S0, K):
    """Computes European Call price under Heston dynamics with closedform solution.
    
    Parameters:
    -----------
        lambd: mean-reversion speed
        vbar: long-term average variance
        eta: volatility of variance
        rho: correlation between stock and vol
        v0: spot variance
        r: risk-free interest rate
        q: dividend rate
        tau: time to maturity in years (365 trading days per year)
        S0: initial spot price
        K: strike price
    """
    today = datetime.date.today()
    ql_date = ql.Date(today.day, today.month, today.year)
    day_count = ql.Actual365Fixed()
    ql.Settings.instance().evaluationDate = ql_date
    
    # option data
    option_type = ql.Option.Call
    payoff = ql.PlainVanillaPayoff(option_type, K)
    maturity_date = ql_date + int(round(tau * 365))
    exercise = ql.EuropeanExercise(maturity_date)
    european_option = ql.VanillaOption(payoff, exercise)
    
    # Heston process
    spot_handle = ql.QuoteHandle(ql.SimpleQuote(S0))
    flat_ts = ql.YieldTermStructureHandle(ql.FlatForward(ql_date, r, day_count))
    dividend_yield = ql.YieldTermStructureHandle(ql.FlatForward(ql_date, q, day_count))
    heston_process = ql.HestonProcess(flat_ts, dividend_yield, spot_handle, v0, lambd, vbar, eta, rho)
    
    engine = ql.AnalyticHestonEngine(ql.HestonModel(heston_process), 1e-15, int(1e6))
    european_option.setPricingEngine(engine)
    
    # check numerical stability
    try:
        price = european_option.NPV()
        if price <= 0 or price + K < S0:
            iv = np.nan
            logging.debug("NumStabProblem: Price {}. Intrinsic {}. Time {}. Strike {}.".format(price, S0-K, tau, K))
        else:
            logging.debug("Success: Price {} > intrinsic {}".format(price, S0-K))
            iv = implied_volatility(price, S0, K, tau, r, 'c')
    except RuntimeError:
        logging.info("RuntimeError: Intrinsic {}. Time {}. Strike {}.".format(S0-K, tau, K))
        price = np.nan
        iv = np.nan
    return price, iv

### Generate labeled data

Load previously generated $(m, T)$ pairs

In [4]:
K_T = pd.read_csv("./data/strike_maturity.csv", index_col=0)

In [5]:
K_T.shape

(1000000, 2)

In [6]:
K_T.head()

   Moneyness  Time to Maturity (years)
0   0.770725                  0.241266
1   0.836500                  0.236654
2   0.763395                  0.248873
3   0.963026                  0.201243
4   0.784699                  0.227981

Initialize the data frame to store labeled data

In [7]:
columns = ['lambda', 'vbar', 'eta', 'rho', 'v0', 'iv']
data_nn = pd.DataFrame(index=K_T.index, columns=columns)
data_nn = pd.concat([K_T, data_nn], axis=1)

In [8]:
data_nn.shape

(1000000, 8)

In [9]:
data_nn.head()

   Moneyness  Time to Maturity (years) lambda vbar  eta  rho   v0   iv
0   0.770725                  0.241266    NaN  NaN  NaN  NaN  NaN  NaN
1   0.836500                  0.236654    NaN  NaN  NaN  NaN  NaN  NaN
2   0.763395                  0.248873    NaN  NaN  NaN  NaN  NaN  NaN
3   0.963026                  0.201243    NaN  NaN  NaN  NaN  NaN  NaN
4   0.784699                  0.227981    NaN  NaN  NaN  NaN  NaN  NaN

Specify model parameters' distribution. For Heston model, we draw the model parameter $\mu = (\eta, \rho, \lambda, \bar{v}, v_0)$ from uniform distribution as proposed in the Table 1 of the paper.

In [10]:
# PARAMETERS
n_samples = K_T.shape[0]

# Heston parameter, bounds by Moodley (2005)
lambd_bounds = [0, 10]
vbar_bounds = [0, 1]
eta_bounds = [0, 5]
rho_bounds = [-1, 0]
v0_bounds = [0, 1]

# Market params
S0 = 1
r = 0
q = 0

In [11]:
data_nn['lambda'] = np.random.uniform(lambd_bounds[0], lambd_bounds[1], n_samples)
data_nn['vbar'] = np.random.uniform(vbar_bounds[0], vbar_bounds[1], n_samples)
data_nn['eta'] = np.random.uniform(eta_bounds[0], eta_bounds[1], n_samples)
data_nn['rho'] = np.random.uniform(rho_bounds[0], rho_bounds[1], n_samples)
data_nn['v0'] = np.random.uniform(v0_bounds[0], v0_bounds[1], n_samples)

In [12]:
data_nn.head()

,Moneyness,Time to Maturity (years),lambda,vbar,eta,rho,v0,iv
0,0.770725,0.241266,7.289124,0.548211,3.390413,-0.165641,0.874642,NaN
1,0.836500,0.236654,8.956104,0.337098,4.198422,-0.938781,0.240779,NaN
2,0.763395,0.248873,5.407095,0.456241,4.359875,-0.287999,0.792108,NaN
3,0.963026,0.201243,1.877246,0.526145,4.863331,-0.441461,0.947103,NaN
4,0.784699,0.227981,5.745099,0.866694,2.537011,-0.155042,0.490160,NaN

Call ```heston_pricer``` to compute the IV

In [13]:
from tqdm import tqdm
tqdm.pandas()  # 为pandas启用进度条

data_nn['iv'] = data_nn.progress_apply(lambda row: heston_pricer(row['lambda'], row['vbar'], row['eta'], 
                                                        row['rho'], row['v0'], r, q, 
                                                        row['Time to Maturity (years)'], S0, row['Moneyness'])[1], axis=1)

  0%|          | 8/1000000 [00:00<8:18:20, 33.44it/s] 2026-01-14 20:45:44,176 - INFO - RuntimeError: Intrinsic 0.06925094152407296. Time 0.2237286223741374. Strike 0.930749058475927.
  0%|          | 66/1000000 [00:00<2:20:52, 118.30it/s]2026-01-14 20:45:44,507 - INFO - RuntimeError: Intrinsic 0.09142277940593435. Time 0.2376443949905655. Strike 0.9085772205940656.
  0%|          | 3086/1000000 [00:09<40:29, 410.33it/s]  2026-01-14 20:45:53,229 - INFO - RuntimeError: Intrinsic 0.1430297616994186. Time 0.1829408283245135. Strike 0.8569702383005814.
  0%|          | 4351/1000000 [00:12<32:12, 515.19it/s]  2026-01-14 20:45:56,452 - INFO - RuntimeError: Intrinsic 0.021539136433007644. Time 0.12341502605422. Strike 0.9784608635669924.
  1%|          | 5561/1000000 [00:15<49:06, 337.49it/s]  2026-01-14 20:45:59,691 - INFO - RuntimeError: Intrinsic 0.07657822690982641. Time 0.1396079091755696. Strike 0.9234217730901736.
  1%|          | 5600/1000000 [00:16<1:15:25, 219.73it/s]2026-01-14 20:46:00,085 - INFO - RuntimeError: Intrinsic 0.08990329103685724. Time 0.1981292161325746. Strike 0.9100967089631428.
  1%|          | 6078/1000000 [00:17<52:33, 315.20it/s]  2026-01-14 20:46:01,840 - INFO - RuntimeError: Intrinsic 0.03819334383608319. Time 0.1900972126940827. Strike 0.9618066561639168.
  1%|          | 6249/1000000 [00:18<55:33, 298.11it/s]  2026-01-14 20:46:02,497 - INFO - RuntimeError: Intrinsic 0.09764432564371839. Time 0.2305010979025802. Strike 0.9023556743562816.
  1%|          | 6322/1000000 [00:19<1:14:03, 223.65it/s]2026-01-14 20:46:02,957 - INFO - RuntimeError: Intrinsic 0.15958662801269763. Time 0.0015955009201968. Strike 0.8404133719873024.
  1%|          | 7253/1000000 [00:21<33:55, 487.68it/s]  2026-01-14 20:46:05,370 - INFO - RuntimeError: Intrinsic 0.1563638634032527. Time 0.2037806302767923. Strike 0.8436361365967473.
  1%|          | 8038/1000000 [00:23<33:31, 493.12it/s]  2026-01-14 20:46:07,592 - INFO - RuntimeError: Intrinsic 0.1888225019955755. Time 0.1787750016107794. Strike 0.8111774980044245.
  1%|          | 8409/1000000 [00:25<45:34, 362.64it/s]  2026-01-14 20:46:08,949 - INFO - RuntimeError: Intrinsic 0.013796742005962814. Time 0.1082268160107822. Strike 0.9862032579940372.
  1%|          | 8516/1000000 [00:25<1:09:29, 237.81it/s]2026-01-14 20:46:09,571 - INFO - RuntimeError: Intrinsic 0.07031523798968442. Time 0.1907009676323734. Strike 0.9296847620103156.
  1%|          | 9135/1000000 [00:27<35:48, 461.21it/s]  2026-01-14 20:46:11,133 - INFO - RuntimeError: Intrinsic 0.16604380990374257. Time 0.1924163074679166. Strike 0.8339561900962574.
  1%|          | 9817/1000000 [00:29<35:20, 467.02it/s]2026-01-14 20:46:13,125 - INFO - RuntimeError: Intrinsic 0.2394161280979954. Time 0.19443124904215. Strike 0.7605838719020046.
  1%|          | 10041/1000000 [00:30<53:34, 307.99it/s] 2026-01-14 20:46:13,994 - INFO - RuntimeError: Intrinsic 0.12543531302299948. Time 0.1636343574342181. Strike 0.8745646869770005.
  1%|          | 10515/1000000 [00:31<38:39, 426.63it/s]  2026-01-14 20:46:15,456 - INFO - RuntimeError: Intrinsic 0.02690913754051083. Time 0.1628178171184852. Strike 0.9730908624594892.
  1%|          | 11295/1000000 [00:33<31:58, 515.48it/s]2026-01-14 20:46:17,284 - INFO - RuntimeError: Intrinsic 0.027832516056069845. Time 0.2049429821464771. Strike 0.9721674839439302.
  1%|▏         | 12674/1000000 [00:36<43:20, 379.62it/s]2026-01-14 20:46:20,613 - INFO - RuntimeError: Intrinsic 0.08523947215990602. Time 0.2402229420567352. Strike 0.914760527840094.
  1%|▏         | 12807/1000000 [00:37<59:24, 276.96it/s]  2026-01-14 20:46:21,144 - INFO - RuntimeError: Intrinsic 0.06526726093513402. Time 0.21305951859074. Strike 0.934732739064866.
2026-01-14 20:46:21,424 - INFO - RuntimeError: Intrinsic 0.16779870873135716. Time 0.1809976093510713. Strike 0.8322012912686428.
  1%|▏         | 13414/1000000 [00:39<29:53, 549.96it/s]  2026-01-14 20:46:22,780 - INFO - RuntimeError: Intrinsic 0.09311532711546644. Time 0.1388739355513803. Strike 0.9068846728845336.
  2%|▏         | 15267/1000000 [00:44<36:34, 448.75it/s]  2026-01-14 20:46:28,231 - INFO - RuntimeError: Intrinsic 0.006889003875601207. Time 0.0914627733511564. Strike 0.9931109961243988.
  2%|▏         | 19252/1000000 [00:55<42:06, 388.22it/s]  2026-01-14 20:46:39,380 - INFO - RuntimeError: Intrinsic 0.009260108495685149. Time 0.2265850853272362. Strike 0.9907398915043149.
  2%|▏         | 21797/1000000 [01:01<48:26, 336.51it/s]  2026-01-14 20:46:45,810 - INFO - RuntimeError: Intrinsic 0.08503086599527143. Time 0.2185471574848072. Strike 0.9149691340047286.
  2%|▏         | 23013/1000000 [01:05<32:43, 497.47it/s]  2026-01-14 20:46:49,260 - INFO - RuntimeError: Intrinsic 0.14944482588838648. Time 0.2267837401610805. Strike 0.8505551741116135.
  2%|▏         | 24050/1000000 [01:08<38:25, 423.25it/s]  2026-01-14 20:46:51,807 - INFO - RuntimeError: Intrinsic -0.00549203224320971. Time 0.2100445815643232. Strike 1.0054920322432097.
  2%|▏         | 24382/1000000 [01:09<41:56, 387.70it/s]  2026-01-14 20:46:52,939 - INFO - RuntimeError: Intrinsic 0.12462602283759006. Time 0.1711514129546519. Strike 0.8753739771624099.
  3%|▎         | 25292/1000000 [01:11<39:01, 416.30it/s]  2026-01-14 20:46:55,420 - INFO - RuntimeError: Intrinsic 0.15840576048499244. Time 0.1349365908011567. Strike 0.8415942395150076.
  3%|▎         | 26099/1000000 [01:13<44:32, 364.36it/s]  2026-01-14 20:46:57,704 - INFO - RuntimeError: Intrinsic 0.22197640519793604. Time 0.2196316018895053. Strike 0.778023594802064.
  3%|▎         | 26455/1000000 [01:15<46:00, 352.65it/s]  2026-01-14 20:46:58,955 - INFO - RuntimeError: Intrinsic 0.205554294616893. Time 0.2053135753217808. Strike 0.794445705383107.
  3%|▎         | 26676/1000000 [01:16<1:01:59, 261.68it/s]2026-01-14 20:46:59,909 - INFO - RuntimeError: Intrinsic 0.08253510658937235. Time 0.2341497556301053. Strike 0.9174648934106276.
  3%|▎         | 27488/1000000 [01:18<42:24, 382.24it/s]  2026-01-14 20:47:02,440 - INFO - RuntimeError: Intrinsic 0.234255089274081. Time 0.1214826208619361. Strike 0.765744910725919.
  3%|▎         | 27888/1000000 [01:19<42:27, 381.54it/s]  2026-01-14 20:47:03,899 - INFO - RuntimeError: Intrinsic 0.24755425749156956. Time 0.2159197960394983. Strike 0.7524457425084304.
  3%|▎         | 28969/1000000 [01:23<35:18, 458.45it/s]  2026-01-14 20:47:07,003 - INFO - RuntimeError: Intrinsic 0.08436099021327759. Time 0.210366291513631. Strike 0.9156390097867224.
  3%|▎         | 29357/1000000 [01:24<50:33, 320.00it/s]  2026-01-14 20:47:08,199 - INFO - RuntimeError: Intrinsic 0.10261999962363677. Time 0.2154328390911522. Strike 0.8973800003763632.
  3%|▎         | 30678/1000000 [01:28<35:37, 453.41it/s]  2026-01-14 20:47:12,388 - INFO - RuntimeError: Intrinsic 0.08740016121546923. Time 0.2487153806954626. Strike 0.9125998387845308.
  3%|▎         | 31899/1000000 [01:31<34:21, 469.59it/s]  2026-01-14 20:47:15,614 - INFO - RuntimeError: Intrinsic 0.15985727998417876. Time 0.2054481773717948. Strike 0.8401427200158212.
2026-01-14 20:47:15,921 - INFO - RuntimeError: Intrinsic 0.18639303106637128. Time 0.1992319727091182. Strike 0.8136069689336287.
  3%|▎         | 31999/1000000 [01:32<1:07:29, 239.06it/s]2026-01-14 20:47:16,385 - INFO - RuntimeError: Intrinsic 0.23992505462120362. Time 0.1689105694037357. Strike 0.7600749453787964.
  3%|▎         | 32445/1000000 [01:34<1:18:39, 205.00it/s]2026-01-14 20:47:18,427 - INFO - RuntimeError: Intrinsic 0.03746244301987123. Time 0.1233450456828356. Strike 0.9625375569801288.
  3%|▎         | 32668/1000000 [01:35<58:44, 274.43it/s]  2026-01-14 20:47:19,194 - INFO - RuntimeError: Intrinsic 0.11970434958061094. Time 0.1351757567952653. Strike 0.8802956504193891.
  3%|▎         | 33481/1000000 [01:37<34:47, 462.95it/s]  2026-01-14 20:47:21,572 - INFO - RuntimeError: Intrinsic 0.21693736899028593. Time 0.1489368373523532. Strike 0.7830626310097141.
2026-01-14 20:47:21,832 - INFO - RuntimeError: Intrinsic 0.10754825557070813. Time 0.246113914272666. Strike 0.8924517444292919.
  3%|▎         | 33817/1000000 [01:39<44:21, 362.96it/s]  2026-01-14 20:47:23,029 - INFO - RuntimeError: Intrinsic 0.08696517942000337. Time 0.2053011102795602. Strike 0.9130348205799966.
  3%|▎         | 34661/1000000 [01:41<48:27, 332.07it/s]  2026-01-14 20:47:25,754 - INFO - RuntimeError: Intrinsic 0.1922915116408539. Time 0.1848430474225881. Strike 0.8077084883591461.
  4%|▎         | 36435/1000000 [01:46<36:01, 445.76it/s]  2026-01-14 20:47:29,916 - INFO - RuntimeError: Intrinsic 0.13042341917139655. Time 0.2178553844908957. Strike 0.8695765808286035.
  4%|▎         | 36821/1000000 [01:47<56:54, 282.11it/s]  2026-01-14 20:47:31,575 - INFO - RuntimeError: Intrinsic 0.09132839594883757. Time 0.2287712748185462. Strike 0.9086716040511624.
  4%|▎         | 36911/1000000 [01:48<1:02:53, 255.23it/s]2026-01-14 20:47:31,974 - INFO - RuntimeError: Intrinsic 0.12048651643933916. Time 0.1940169926163197. Strike 0.8795134835606608.
  4%|▎         | 37374/1000000 [01:49<36:27, 439.99it/s]  2026-01-14 20:47:33,345 - INFO - RuntimeError: Intrinsic 0.2002081512825311. Time 0.1574791875479825. Strike 0.7997918487174689.
2026-01-14 20:47:33,694 - INFO - RuntimeError: Intrinsic 0.22229299303405403. Time 0.2359415576709723. Strike 0.777707006965946.
  4%|▎         | 37486/1000000 [01:50<1:06:07, 242.61it/s]2026-01-14 20:47:34,199 - INFO - RuntimeError: Intrinsic 0.05149080484244162. Time 0.1987091943693711. Strike 0.9485091951575584.
  4%|▍         | 38158/1000000 [01:52<39:30, 405.72it/s]  2026-01-14 20:47:36,383 - INFO - RuntimeError: Intrinsic 0.18804046812501873. Time 0.2283983408904438. Strike 0.8119595318749813.
  4%|▍         | 39013/1000000 [01:55<39:54, 401.26it/s]  2026-01-14 20:47:38,924 - INFO - RuntimeError: Intrinsic -0.03259648468774112. Time 0.2418044075061757. Strike 1.0325964846877411.
  4%|▍         | 39161/1000000 [01:55<55:35, 288.06it/s]  2026-01-14 20:47:39,706 - INFO - RuntimeError: Intrinsic 0.12355568173881026. Time 0.2407822039247436. Strike 0.8764443182611897.
  4%|▍         | 39720/1000000 [01:57<51:40, 309.70it/s]  2026-01-14 20:47:41,433 - INFO - RuntimeError: Intrinsic 0.13003650738353278. Time 0.2468956049734159. Strike 0.8699634926164672.
  4%|▍         | 39956/1000000 [01:58<42:44, 374.40it/s]  2026-01-14 20:47:42,152 - INFO - RuntimeError: Intrinsic 0.062112621047233585. Time 0.2086352494490161. Strike 0.9378873789527664.
  4%|▍         | 42206/1000000 [02:04<47:42, 334.64it/s]  2026-01-14 20:47:48,464 - INFO - RuntimeError: Intrinsic 0.13243780913101. Time 0.2249494955607018. Strike 0.86756219086899.
  4%|▍         | 42368/1000000 [02:05<1:18:17, 203.87it/s]2026-01-14 20:47:49,675 - INFO - RuntimeError: Intrinsic 0.17774997839321782. Time 0.178311039029671. Strike 0.8222500216067822.
  4%|▍         | 42414/1000000 [02:06<2:14:37, 118.55it/s]2026-01-14 20:47:50,317 - INFO - RuntimeError: Intrinsic 0.15433844694687682. Time 0.1618880163025843. Strike 0.8456615530531232.
  4%|▍         | 42573/1000000 [02:07<1:06:32, 239.79it/s]2026-01-14 20:47:50,969 - INFO - RuntimeError: Intrinsic 0.02234725884849542. Time 0.2283724423244157. Strike 0.9776527411515046.
  4%|▍         | 42737/1000000 [02:07<55:33, 287.20it/s]  2026-01-14 20:47:51,683 - INFO - RuntimeError: Intrinsic 0.17758082161940403. Time 0.2302289293233331. Strike 0.822419178380596.
  4%|▍         | 43386/1000000 [02:09<45:15, 352.31it/s]  2026-01-14 20:47:53,687 - INFO - RuntimeError: Intrinsic 0.031015345200148037. Time 0.1755488486788202. Strike 0.968984654799852.
  4%|▍         | 44003/1000000 [02:12<1:12:44, 219.02it/s]2026-01-14 20:47:56,028 - INFO - RuntimeError: Intrinsic 0.22429771774969165. Time 0.2454862766048866. Strike 0.7757022822503084.
  4%|▍         | 44061/1000000 [02:12<1:36:23, 165.30it/s]2026-01-14 20:47:56,505 - INFO - RuntimeError: Intrinsic 0.04515931718626043. Time 0.2135254632739359. Strike 0.9548406828137396.
  5%|▍         | 45147/1000000 [02:16<37:24, 425.33it/s]  2026-01-14 20:48:00,225 - INFO - RuntimeError: Intrinsic 0.2228272403161322. Time 0.218713346108497. Strike 0.7771727596838678.
  5%|▍         | 45286/1000000 [02:16<54:54, 289.82it/s]  2026-01-14 20:48:00,759 - INFO - RuntimeError: Intrinsic 0.12167137439047415. Time 0.2222846006381738. Strike 0.8783286256095258.
  5%|▍         | 46948/1000000 [02:22<1:02:11, 255.41it/s]2026-01-14 20:48:06,288 - INFO - RuntimeError: Intrinsic 0.10726614467640827. Time 0.2349661211203712. Strike 0.8927338553235917.
  5%|▍         | 47393/1000000 [02:24<41:28, 382.73it/s]  2026-01-14 20:48:07,985 - INFO - RuntimeError: Intrinsic 0.13804190335346478. Time 0.2339897973873147. Strike 0.8619580966465352.
  5%|▍         | 48725/1000000 [02:28<34:50, 454.99it/s]  2026-01-14 20:48:12,436 - INFO - RuntimeError: Intrinsic 0.24532128360095806. Time 0.0857707543794381. Strike 0.7546787163990419.
  5%|▍         | 49020/1000000 [02:29<47:48, 331.56it/s]  2026-01-14 20:48:13,546 - INFO - RuntimeError: Intrinsic 0.03415386475828763. Time 0.2432189461701501. Strike 0.9658461352417124.
  5%|▌         | 50067/1000000 [02:33<1:02:57, 251.48it/s]2026-01-14 20:48:16,951 - INFO - RuntimeError: Intrinsic 0.11920701092598507. Time 0.2274592637965061. Strike 0.8807929890740149.
  5%|▌         | 50843/1000000 [02:35<51:05, 309.67it/s]  2026-01-14 20:48:19,511 - INFO - RuntimeError: Intrinsic 0.021676524140806563. Time 0.2459338677285577. Strike 0.9783234758591934.
  5%|▌         | 50983/1000000 [02:36<49:39, 318.48it/s]  2026-01-14 20:48:20,018 - INFO - RuntimeError: Intrinsic 0.15615649630722828. Time 0.1993578550200136. Strike 0.8438435036927717.
  5%|▌         | 51196/1000000 [02:37<58:20, 271.08it/s]  2026-01-14 20:48:21,065 - INFO - RuntimeError: Intrinsic -0.09213412545293975. Time 0.2342082691317591. Strike 1.0921341254529398.
  5%|▌         | 51763/1000000 [02:38<42:04, 375.58it/s]  2026-01-14 20:48:22,681 - INFO - RuntimeError: Intrinsic 0.08604600194581358. Time 0.200075948460133. Strike 0.9139539980541864.
2026-01-14 20:48:22,971 - INFO - RuntimeError: Intrinsic 0.21340449053437283. Time 0.0960964562763994. Strike 0.7865955094656272.
  5%|▌         | 53375/1000000 [02:43<38:19, 411.73it/s]  2026-01-14 20:48:27,009 - INFO - RuntimeError: Intrinsic 0.14267925576394724. Time 0.1961650425668923. Strike 0.8573207442360528.
  5%|▌         | 53422/1000000 [02:43<1:12:38, 217.20it/s]2026-01-14 20:48:27,651 - INFO - RuntimeError: Intrinsic 0.13306955071815185. Time 0.2439348988762352. Strike 0.8669304492818481.
  5%|▌         | 53458/1000000 [02:44<1:40:29, 156.99it/s]2026-01-14 20:48:28,048 - INFO - RuntimeError: Intrinsic 0.12400782838681579. Time 0.236869477375593. Strike 0.8759921716131842.
  5%|▌         | 54567/1000000 [02:47<40:49, 386.04it/s]  2026-01-14 20:48:31,780 - INFO - RuntimeError: Intrinsic 0.1593617253140016. Time 0.2203111237799337. Strike 0.8406382746859984.
  5%|▌         | 54997/1000000 [02:49<47:56, 328.55it/s]  2026-01-14 20:48:33,295 - INFO - RuntimeError: Intrinsic 0.05253844577908118. Time 0.1528729838069652. Strike 0.9474615542209188.
  6%|▌         | 55215/1000000 [02:50<40:34, 388.10it/s]  2026-01-14 20:48:33,928 - INFO - RuntimeError: Intrinsic 0.22925632811169738. Time 0.2345435610240092. Strike 0.7707436718883026.
  6%|▌         | 55469/1000000 [02:51<46:26, 338.92it/s]  2026-01-14 20:48:35,050 - INFO - RuntimeError: Intrinsic 0.06508720404210955. Time 0.1917761842095595. Strike 0.9349127959578905.
  6%|▌         | 56131/1000000 [02:53<38:31, 408.29it/s]  2026-01-14 20:48:37,112 - INFO - RuntimeError: Intrinsic 0.10204020694278482. Time 0.2468033329176013. Strike 0.8979597930572152.
  6%|▌         | 56403/1000000 [02:54<41:37, 377.79it/s]  2026-01-14 20:48:38,001 - INFO - RuntimeError: Intrinsic 0.08501108970896298. Time 0.2226104953055551. Strike 0.914988910291037.
  6%|▌         | 57435/1000000 [02:56<1:00:03, 261.56it/s]2026-01-14 20:48:40,860 - INFO - RuntimeError: Intrinsic 0.1459517222875184. Time 0.2253740759839961. Strike 0.8540482777124816.
  6%|▌         | 58776/1000000 [03:00<54:18, 288.83it/s]  2026-01-14 20:48:44,238 - INFO - RuntimeError: Intrinsic -0.01143976151914905. Time 0.2159085178279413. Strike 1.011439761519149.
  6%|▌         | 58902/1000000 [03:00<55:07, 284.52it/s]  2026-01-14 20:48:44,760 - INFO - RuntimeError: Intrinsic 0.07915930882161037. Time 0.2074342173565817. Strike 0.9208406911783896.
  6%|▌         | 58940/1000000 [03:01<1:16:51, 204.05it/s]2026-01-14 20:48:45,074 - INFO - RuntimeError: Intrinsic 0.08419456129812519. Time 0.2191323017813428. Strike 0.9158054387018748.
  6%|▌         | 60203/1000000 [03:04<43:49, 357.35it/s]  2026-01-14 20:48:48,762 - INFO - RuntimeError: Intrinsic 0.16515721955617568. Time 0.1327342149646433. Strike 0.8348427804438243.
  6%|▌         | 60246/1000000 [03:05<1:09:30, 225.32it/s]2026-01-14 20:48:49,175 - INFO - RuntimeError: Intrinsic 0.03833885584866081. Time 0.2390076507591773. Strike 0.9616611441513392.
  6%|▌         | 60495/1000000 [03:06<50:35, 309.48it/s]  2026-01-14 20:48:50,045 - INFO - RuntimeError: Intrinsic 0.09296177054877841. Time 0.2354117595488154. Strike 0.9070382294512216.
  6%|▌         | 61493/1000000 [03:08<32:49, 476.62it/s]  2026-01-14 20:48:52,664 - INFO - RuntimeError: Intrinsic 0.025300241480900043. Time 0.2031212404356581. Strike 0.9746997585191.
  6%|▌         | 61679/1000000 [03:09<45:03, 347.02it/s]2026-01-14 20:48:53,339 - INFO - RuntimeError: Intrinsic 0.20533678188191684. Time 0.2419905703312376. Strike 0.7946632181180832.
  6%|▋         | 62559/1000000 [03:12<44:25, 351.70it/s]  2026-01-14 20:48:56,127 - INFO - RuntimeError: Intrinsic 0.11473106305509528. Time 0.1672191242306641. Strike 0.8852689369449047.
  6%|▋         | 63461/1000000 [03:14<35:03, 445.22it/s]  2026-01-14 20:48:58,640 - INFO - RuntimeError: Intrinsic 0.22030523248208067. Time 0.246514070506136. Strike 0.7796947675179193.
  6%|▋         | 63508/1000000 [03:15<58:38, 266.12it/s]2026-01-14 20:48:59,069 - INFO - RuntimeError: Intrinsic 0.055704914599600586. Time 0.1503956210329368. Strike 0.9442950854003994.
  6%|▋         | 64562/1000000 [03:18<53:35, 290.91it/s]  2026-01-14 20:49:02,366 - INFO - RuntimeError: Intrinsic 0.20534522293700597. Time 0.2076431081820828. Strike 0.794654777062994.
  7%|▋         | 65053/1000000 [03:20<47:03, 331.14it/s]  2026-01-14 20:49:03,976 - INFO - RuntimeError: Intrinsic 0.13914969273733335. Time 0.2289591503222585. Strike 0.8608503072626666.
  7%|▋         | 65420/1000000 [03:21<1:01:19, 253.98it/s]2026-01-14 20:49:05,469 - INFO - RuntimeError: Intrinsic 0.07167887215655722. Time 0.2486293257420941. Strike 0.9283211278434428.
  7%|▋         | 65775/1000000 [03:23<1:01:05, 254.84it/s]2026-01-14 20:49:07,117 - INFO - RuntimeError: Intrinsic 0.1773870519170334. Time 0.2342757701319066. Strike 0.8226129480829666.
  7%|▋         | 65857/1000000 [03:23<1:05:53, 236.27it/s]2026-01-14 20:49:07,566 - INFO - RuntimeError: Intrinsic 0.19700173073763372. Time 0.246796737501294. Strike 0.8029982692623663.
  7%|▋         | 66174/1000000 [03:25<51:46, 300.61it/s]  2026-01-14 20:49:08,833 - INFO - RuntimeError: Intrinsic 0.01852188705913782. Time 0.1865422829699614. Strike 0.9814781129408622.
  7%|▋         | 67038/1000000 [03:27<42:28, 366.09it/s]  2026-01-14 20:49:11,330 - INFO - RuntimeError: Intrinsic 0.1013019859665214. Time 0.2373869067594058. Strike 0.8986980140334786.
  7%|▋         | 67381/1000000 [03:28<41:35, 373.72it/s]  2026-01-14 20:49:12,293 - INFO - RuntimeError: Intrinsic 0.14759783502294366. Time 0.173152545061395. Strike 0.8524021649770563.
  7%|▋         | 68385/1000000 [03:31<56:53, 272.93it/s]  2026-01-14 20:49:15,606 - INFO - RuntimeError: Intrinsic 0.12977602340557848. Time 0.2436810103246114. Strike 0.8702239765944215.
  7%|▋         | 69430/1000000 [03:35<37:11, 417.06it/s]  2026-01-14 20:49:18,880 - INFO - RuntimeError: Intrinsic 0.21675208609900054. Time 0.2217706777421256. Strike 0.7832479139009995.

Drop ```NaN``` data

In [14]:
data_nn.dropna(inplace=True)

In [15]:
data_nn.shape

(998348, 8)

Split generated labeled data into ```train```, ```val``` and ```test```

In [16]:
# data_nn = data_nn.iloc[:990000, :]
data_nn.reset_index(drop=True, inplace=True)

data_train, data_val, data_test = np.split(data_nn, [int(9e5), int(9.45e5)], axis=0)
data_train.shape, data_val.shape, data_test.shape

((900000, 8), (45000, 8), (53348, 8))

Store splitted data to local files

In [ ]:
# data_train.to_csv("./data/heston/train.csv", index=False)

# train data
length1 = len(data_train) // 2
df1 = data_train.iloc[:length1, :]
df2 = data_train.iloc[length1:, :]
df1.to_csv('data/heston/train1.csv', index=False)
df2.to_csv('data/heston/train2.csv', index=False)

# val data
data_val.to_csv("./data/heston/val.csv", index=False)

# test data
data_test.to_csv("./data/heston/test.csv", index=False)

----------

----------

## Generate rBergomi data

In [1]:
import numpy as np
from matplotlib import pyplot as plt
from rbergomi.rbergomi import rBergomi

%matplotlib inline

Define rBergomi pricer with Cholesky decomposition method, and Monte Carlo simulation

In [2]:
def rBergomi_pricer(H, eta, rho, v0, tau, K, S0, MC_samples=40000):
    """Computes European Call price under rBergomi dynamics with MC sampling.
    
    Parameters:
    -----------
        H: Hurst parameter
        eta: volatility of variance
        rho: correlation between stock and vol
        v0: spot variance
        tau: time to maturity in years (365 trading days per year)
        K: strike price
    """
    try:
        rB = rBergomi(n=365, N=MC_samples, T=tau, a=H-0.5)
        dW1, dW2 = rB.dW1(), rB.dW2()
        Y = rB.Y(dW1)
        dB = rB.dB(dW1, dW2, rho)
        xi = v0
        V = rB.V(Y, xi, eta)
        S = rB.S(V, dB)
        ST = S[:, -1]
        price = np.mean(np.maximum(ST-K, 0))
    except:
        return np.nan, np.nan
    
    # check numerical stability
    if price <= 0 or price + K < S0:
        iv = np.nan
        logging.debug("NumStabProblem: Price {}. Intrinsic {}. Time {}. Strike {}.".format(price, S0-K, tau, K))
    else:
        logging.debug("Success: Price {} > intrinsic {}".format(price, S0-K))
        iv = implied_volatility(price, S0, K, tau, 0, 'c')
    return price, iv

### Generate rBergomi labeled data

Load previously generated $(m,T)$ data

In [200]:
K_T = pd.read_csv("./data/strike_maturity.csv", index_col=0)

In [201]:
K_T.shape

(1000000, 2)

In [202]:
K_T.head()

   Moneyness  Time to Maturity (years)
0   0.820165                  0.219184
1   0.926490                  0.212487
2   0.834318                  0.190719
3   1.053977                  0.226441
4   0.802749                  0.208923

In [204]:
# PARAMETERS
n_samples = K_T.shape[0]

# Market params
S0 = 1.

Define rBergomi parameter generator with ```scipy.stats.truncnorm```

In [ ]:
from scipy.stats import truncnorm

def param_generator(H_generator=truncnorm(-1.2, 8.6, 0.07, 0.05), 
                    eta_generator=truncnorm(-3, 3, 2.5, 0.5), 
                    rho_generator=truncnorm(-0.25, 2.25, -0.95, 0.2), 
                    v0_generator=truncnorm(-2.5, 7, 0.3, 0.1)):
    rslt = {
        'H': H_generator.rvs(),
        'eta': eta_generator.rvs(),
        'rho': rho_generator.rvs(),
        'v0': v0_generator.rvs() ** 2
    }
    return rslt

In [205]:
def generate_rBergomi_sample(K, T, param_generator, S0=1.0):
    """ Generates a rBergomi sample with random parameters
    """
    counter = 0
    while counter < 10:
        params = param_generator()
        H, eta, rho, v0 = params['H'], params['eta'], params['rho'], params['v0']
        _, iv = rBergomi_pricer(H, eta, rho, v0, T, K, S0)
        if np.isnan(iv):
            counter += 1
        else:
            break
    else:
        logging.warning("Tried 10 times, none valid sample obtained.")
    sample = {
        'H': H,
        'eta': eta,
        'rho': rho,
        'v0': v0,
        'iv': iv
    }
    return sample

Generate labeled data

**NB**: The next cells are executable, but it takes too long a time to generate $10^6$ samples, so in practice we generated only half of that on a cloud-based virtual machine.

In [ ]:
data_nn = K_T.merge(K_T.progress_apply(
    lambda row: pd.Series(generate_rBergomi_sample(row['Moneyness'], row['Time to Maturity (years)'], param_generator, S0)), 
    axis=1), left_index=True, right_index=True)

In [ ]:
data_nn.dropna(inplace=True)

In [ ]:
data_nn.shape

In [ ]:
data_nn.head()

In [ ]:
data_nn.to_csv("./data/rBergomi/labeled_data_all.csv", index=False)

In [ ]:
# data_nn = data_nn.iloc[:990000, :]
data_nn.reset_index(drop=True, inplace=True)

# Dissecting labeled pairs into training, validation and testing sets.

data_train, data_val, data_test = np.split(data_nn, [int(9e5), int(9.5e5)], axis=0)

data_train.shape, data_val.shape, data_test.shape

In [ ]:
data_train.to_csv("./data/heston/train.csv", index=False)
data_val.to_csv("./data/heston/val.csv", index=False)
data_test.to_csv("./data/heston/test.csv", index=False)

# References

[1] https://github.com/ryanmccrickerd/rough_bergomi

[2] https://github.com/amuguruza/RoughFCLT/blob/master/rDonsker.ipynb